---
- name: Create the network configuration file for bond devices
  become: true
  template:
    src: 'bond_{{ ansible_facts.os_family }}.j2'
    dest: '{{ interfaces_net_path }}/ifcfg-{{ item.device }}'
  with_items: '{{ interfaces_bond_interfaces }}'
  register: bond_result
  notify:
    - Check whether /etc/modules-load.d exists
    - Make sure the bonding module is loaded
    - Make sure the bonding module is loaded at boot via /etc/modules-load.d
    - Make sure the bonding module is loaded at boot via /etc/modules
    - Bounce network devices

- name: Create the network configuration file for slave in the bond devices
  become: true
  template:
    src: 'bond_slave_{{ ansible_facts.os_family }}.j2'
    dest: '{{ interfaces_net_path }}/ifcfg-{{ item.1 }}'
  with_subelements:
    - "{{ interfaces_bond_interfaces }}"
    - bond_slaves
  when:
    - interfaces_bond_setup_slaves
  register: bond_slave_result
  notify:
    - Bounce network devices

